[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.66.3",
    "schedule>=1.2.2",
    "streamlit>=1.43.2",
    "trafilatura>=2.0.0",
]
